### ISSUE TITLE
Morning session peer to peer review

### ISSUE THREAD

**Issue by Ashe546** [brainconnect93/Capstone-project#2]
-HI @brainconnect93 your project is well done and accordingly to the requirements made by microverse.

 **NO linter error**
 **Good workflow**
**documented your work in a professional way**

###   **Optional suggestions to make changes to**

- [ ] Kindly add the link to your deployed version of your project.
- [ ] On your script.js file while you render your speakers instead of using for loop it is advised you use for each.  
- [ ] kindly use the arrow function instead of default functions, using the arrow function decreases the size of your code and increases 
readability.
- [ ] Kindly add a descriptive ALT IMG tag, so that the reader understands when the page loads slow.

**Comment by brainconnect93** [comment]
Thanks, @Ashe546  I have rectified the issue raised
